version: '3'
services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: pipeline
      POSTGRES_PASSWORD: pipeline-pass
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whats-for-dinner-app
    command: [ "poetry", "run", "start" ]
    environment:
      - OPENAI_API_KEY=place-your-key-here
      - PG_CONN_STR=postgresql://pipeline:pipeline-pass@localhost:5432/challenge
    depends_on:
      - db
    ports:
      - "8080:8080"
